######################################################################
# Automatically generated by qmake (2.01a) Mi. Nov 24 08:29:39 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
QMAKE_CXXFLAGS += -g

# Input
HEADERS += JItemHistModel.hpp JHistModel.hpp JHistView.hpp QHisto.xpm
SOURCES += JItemHistModel.cpp JHistModel.cpp JHistView.cpp main.cpp
