.TH QHISTO 5 "2010-11-27" "v1" "Histogram display"

.SH NAME
QHisto \- Format of QHisto files

.SH DEFINITIONS
The key words "MUST", "MUST NOT", "REQUIRED", "SHALL", "SHALL
NOT", "SHOULD", "SHOULD NOT", "RECOMMENDED",  "MAY", and
"OPTIONAL" in this document are to be interpreted as described in
RFC 2119.

.SH DESCRIPTION
A QHisto file consists of one or more lines, each separated
by a line feed, or a carriage return followed by a line
feed; implementations shall write a line feed only. Each
line shall consist of valid UTF-8 sequences.

A QHisto file may contain comment lines and data lines, which
are described hereinafter. It must contain at least one data
line to be valid.

.SS Comment lines
A line starting with the symbol '#' is a comment line. Implementations
shall ignore comment lines when representing the data, but may keep
comment lines when rewriting a file.

.SS Data line format
Each line consists of three fields, separated by a tabulator, that
is:

.RS
\fIlabel\fR\\t\fIvalue\fR\\t\fIcolor\fR
.RE

The first three fields have the following meaning:
.RS
.TP
.I label
A short description of the value that will be displayed alongside
with it.
.TP
.I value
A number represented in radix 10. This field may contain any value
conforming to the following extended POSIX regular expression:

    [+-]?[0-9](\.[0-9])?([eE][+-]?[0-9])?

.TP
.I color
A string specifying a color. This can either be a hexadecimal
identifier in one of the forms #RGB, #RRGGBB, #RRRGGGBBB, or
#RRRRGGGGBBBB; or one of the color keyword names from the SVG
1.1 (Second Edition), section 4.4.
.RE

Further fields may be added in future revisions.

.SS Escaping special characters
Unless otherwise specified, a field of a data line shall
replace characters listed in the following table with the
escape sequence defined in the table.

    character   Unicode  escape sequence  notes
    ---------   -------  ---------------  -----
    line-feed   U+000A   \\n
    return      U+000D   \\r
    tabulator   U+0009   \\t
    #           U+0023   \\#               [1]
    \\           U+005C   \\\\

    [1] The character may be kept as it if it is not the
        first character of a line.

.SH INTEROPERABILITY
A file in the QHisto format containing no escape sequences can be
converted into a RFC 4180 conforming document by removing all comment
lines, replacing the new-line separator by a carriage return followed
by a line feed, and replacing the tabulator by a comma.

.SH AUTHOR
QHisto and its manual pages were written by Julian Andres Klode
<jak@jak-linux.org>.

.SH "SEE ALSO"
.BR QHisto (1),
.BR qtoptions (7),
.BR RFC\ 4180
