######################################################################
# Automatically generated by qmake (2.01a) Mi. Nov 24 08:29:39 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
QMAKE_CXXFLAGS += -g

# Input
HEADERS += JItemHistoModel.hpp JHistoModel.hpp JHistoView.hpp
SOURCES += JItemHistoModel.cpp JHistoModel.cpp JHistoView.cpp main.cpp
